In [51]:
import pandas as pd
import numpy as np

In [52]:
data = pd.read_csv("C:/Users/91986/Downloads/ai tasks/matches.csv")


In [53]:
data.head()


Unnamed: 0     Season        Date           Home   xG  Home Goals  \
0           0  2023/2024  2023-08-11        Burnley  0.3         0.0   
1           1  2023/2024  2023-08-12        Arsenal  0.8         2.0   
2           2  2023/2024  2023-08-12        Everton  2.7         0.0   
3           3  2023/2024  2023-08-12  Sheffield Utd  0.5         0.0   
4           4  2023/2024  2023-08-12       Brighton  4.0         4.0   

   Away Goals  xG.1             Away  Attendance  \
0         3.0   1.9  Manchester City     21572.0   
1         1.0   1.2  Nott'ham Forest     59984.0   
2         1.0   1.5           Fulham     39940.0   
3         1.0   1.9   Crystal Palace     31194.0   
4         1.0   1.5       Luton Town     31872.0   

                                    Venue  
0                               Turf Moor  
1                        Emirates Stadium  
2                           Goodison Park  
3                            Bramall Lane  
4  The American Express Community Stadium

In [54]:
data.describe()


Unnamed: 0           xG    Home Goals    Away Goals         xG.1  \
count  60529.000000  2660.000000  50568.000000  50568.000000  2660.000000   
mean     248.176444     1.504361      1.801100      1.172540     1.228496   
std      149.038937     0.851252      1.464901      1.146355     0.753071   
min        0.000000     0.000000      0.000000      0.000000     0.000000   
25%      121.000000     0.900000      1.000000      0.000000     0.700000   
50%      243.000000     1.400000      2.000000      1.000000     1.100000   
75%      368.000000     2.000000      3.000000      2.000000     1.600000   
max      628.000000     7.000000     12.000000      9.000000     4.600000   

         Attendance  
count  11446.000000  
mean   33295.807968  
std    14223.190117  
min     2000.000000  
25%    23246.000000  
50%    31130.000000  
75%    40162.000000  
max    83222.000000

In [55]:
data.shape


(60529, 11)

In [56]:
data.nunique()


Unnamed: 0     629
Season         125
Date          9822
Home            70
xG              51
Home Goals      13
Away Goals      10
xG.1            46
Away            70
Attendance    9392
Venue           77
dtype: int64

In [57]:
data.columns

Index(['Unnamed: 0', 'Season', 'Date', 'Home', 'xG', 'Home Goals',
       'Away Goals', 'xG.1', 'Away', 'Attendance', 'Venue'],
      dtype='object')

In [58]:
data=data.drop(['Attendance', 'Venue'],axis=1)

In [59]:
data.columns

Index(['Unnamed: 0', 'Season', 'Date', 'Home', 'xG', 'Home Goals',
       'Away Goals', 'xG.1', 'Away'],
      dtype='object')

In [60]:
x=data[['Season','Home', 'xG', 'Home Goals', 'Away Goals', 'xG.1','Away']].values

In [61]:
x


array([['2023/2024', 'Burnley', 0.3, ..., 3.0, 1.9, 'Manchester City'],
       ['2023/2024', 'Arsenal', 0.8, ..., 1.0, 1.2, "Nott'ham Forest"],
       ['2023/2024', 'Everton', 2.7, ..., 1.0, 1.5, 'Fulham'],
       ...,
       ['1888/1889', nan, nan, ..., nan, nan, nan],
       ['1888/1889', 'Blackburn', nan, ..., 0.0, nan, 'Derby County'],
       ['1888/1889', 'Accrington', nan, ..., 0.0, nan, 'Stoke']],
      dtype=object)

In [62]:
y=data[['Date']].values

In [63]:
y

array([['2023-08-11'],
       ['2023-08-12'],
       ['2023-08-12'],
       ...,
       [nan],
       ['1889-04-14'],
       ['1889-04-19']], dtype=object)

In [64]:
from sklearn.impute import SimpleImputer

In [65]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')

In [66]:
imputer=imputer.fit(x[:,2:6])

In [67]:
x[:,2:6]=imputer.transform(x[:,2:6])

In [68]:
x


array([['2023/2024', 'Burnley', 0.3, ..., 3.0, 1.9, 'Manchester City'],
       ['2023/2024', 'Arsenal', 0.8, ..., 1.0, 1.2, "Nott'ham Forest"],
       ['2023/2024', 'Everton', 2.7, ..., 1.0, 1.5, 'Fulham'],
       ...,
       ['1888/1889', nan, 1.504360902255639, ..., 1.1725399462110426,
        1.2284962406015039, nan],
       ['1888/1889', 'Blackburn', 1.504360902255639, ..., 0.0,
        1.2284962406015039, 'Derby County'],
       ['1888/1889', 'Accrington', 1.504360902255639, ..., 0.0,
        1.2284962406015039, 'Stoke']], dtype=object)

In [69]:
from sklearn.preprocessing import LabelEncoder

In [70]:
label_encode_x=LabelEncoder()

In [71]:
x[:,0]=label_encode_x.fit_transform(x[:,0])

In [72]:
x


array([[124, 'Burnley', 0.3, ..., 3.0, 1.9, 'Manchester City'],
       [124, 'Arsenal', 0.8, ..., 1.0, 1.2, "Nott'ham Forest"],
       [124, 'Everton', 2.7, ..., 1.0, 1.5, 'Fulham'],
       ...,
       [0, nan, 1.504360902255639, ..., 1.1725399462110426,
        1.2284962406015039, nan],
       [0, 'Blackburn', 1.504360902255639, ..., 0.0, 1.2284962406015039,
        'Derby County'],
       [0, 'Accrington', 1.504360902255639, ..., 0.0, 1.2284962406015039,
        'Stoke']], dtype=object)

In [73]:
x[:,1]=label_encode_x.fit_transform(x[:,1])

In [74]:
x[:,6]=label_encode_x.fit_transform(x[:,6])

In [75]:
x

array([[124, 15, 0.3, ..., 3.0, 1.9, 37],
       [124, 1, 0.8, ..., 1.0, 1.2, 45],
       [124, 25, 2.7, ..., 1.0, 1.5, 26],
       ...,
       [0, 70, 1.504360902255639, ..., 1.1725399462110426,
        1.2284962406015039, 70],
       [0, 6, 1.504360902255639, ..., 0.0, 1.2284962406015039, 24],
       [0, 0, 1.504360902255639, ..., 0.0, 1.2284962406015039, 57]],
      dtype=object)

In [76]:
from sklearn.preprocessing import OneHotEncoder

In [77]:
onehotencoder=OneHotEncoder()

In [78]:
labelencoder_y=LabelEncoder()

In [79]:
y=labelencoder_y.fit_transform(y)

C:\Users\91986\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [80]:
y

array([9702, 9703, 9703, ..., 9822,   36,   37])

In [81]:
from sklearn.model_selection import train_test_split

In [82]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [83]:
x_train

array([[53, 8, 1.504360902255639, ..., 1.0, 1.2284962406015039, 38],
       [95, 21, 1.504360902255639, ..., 1.0, 1.2284962406015039, 2],
       [122, 64, 0.5, ..., 2.0, 1.6, 13],
       ...,
       [39, 20, 1.504360902255639, ..., 1.0, 1.2284962406015039, 41],
       [37, 37, 1.504360902255639, ..., 2.0, 1.2284962406015039, 49],
       [118, 20, 1.5, ..., 0.0, 0.1, 60]], dtype=object)

In [84]:
x_test

array([[51, 39, 1.504360902255639, ..., 3.0, 1.2284962406015039, 19],
       [10, 62, 1.504360902255639, ..., 1.0, 1.2284962406015039, 24],
       [51, 63, 1.504360902255639, ..., 4.0, 1.2284962406015039, 7],
       ...,
       [18, 70, 1.504360902255639, ..., 1.1725399462110426,
        1.2284962406015039, 70],
       [29, 70, 1.504360902255639, ..., 1.1725399462110426,
        1.2284962406015039, 70],
       [88, 70, 1.504360902255639, ..., 1.1725399462110426,
        1.2284962406015039, 70]], dtype=object)

In [85]:
y_train

array([3323, 6657, 9533, ..., 2467, 2314, 9036])

In [86]:
y_test

array([3192,  533, 3167, ..., 9822, 9822, 9822])

In [87]:
from sklearn.preprocessing import StandardScaler

In [88]:
scx=StandardScaler()

In [89]:
x_train=scx.fit_transform(x_train)

In [90]:
x_test=scx.transform(x_test)

In [91]:
x_train

array([[-2.79801087e-01, -1.42354058e+00,  1.14915918e-03, ...,
        -1.67621090e-01, -5.03456156e-03, -1.15326854e-01],
       [ 9.60567147e-01, -8.55583982e-01,  1.14915918e-03, ...,
        -1.67621090e-01, -5.03456156e-03, -1.68960018e+00],
       [ 1.75794673e+00,  1.02304167e+00, -5.66056956e+00, ...,
         7.84639871e-01,  2.31028587e+00, -1.20857222e+00],
       ...,
       [-6.93257165e-01, -8.99272951e-01,  1.14915918e-03, ...,
        -1.67621090e-01, -5.03456156e-03,  1.58625900e-02],
       [-7.52322319e-01, -1.56560483e-01,  1.14915918e-03, ...,
         7.84639871e-01, -5.03456156e-03,  3.65701108e-01],
       [ 1.63981642e+00, -8.99272951e-01, -2.34338387e-02, ...,
        -1.11988205e+00, -7.03815423e+00,  8.46729070e-01]])

In [92]:
x_test

array([[-3.38866241e-01, -6.91825461e-02,  1.14915918e-03, ...,
         1.73690083e+00, -5.03456156e-03, -9.46193334e-01],
       [-1.54970190e+00,  9.35663734e-01,  1.14915918e-03, ...,
        -1.67621090e-01, -5.03456156e-03, -7.27544261e-01],
       [-3.38866241e-01,  9.79352702e-01,  1.14915918e-03, ...,
         2.68916179e+00, -5.03456156e-03, -1.47095111e+00],
       ...,
       [-1.31344128e+00,  1.28517548e+00,  1.14915918e-03, ...,
        -3.31803518e-03, -5.03456156e-03,  1.28402722e+00],
       [-9.88582935e-01,  1.28517548e+00,  1.14915918e-03, ...,
        -3.31803518e-03, -5.03456156e-03,  1.28402722e+00],
       [ 7.53839108e-01,  1.28517548e+00,  1.14915918e-03, ...,
        -3.31803518e-03, -5.03456156e-03,  1.28402722e+00]])

In [93]:
#TASK 3

In [94]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import xgboost as xgb

# Train model
model = xgb.XGBRegressor(objective ='reg:squarederror', n_estimators=100, learning_rate=0.1, max_depth=5, random_state=42)
model.fit(x_train, y_train)

# Evaluate model
y_pred = model.predict(x_test)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"RMSE: {rmse}")
print(f"R^2 Score: {r2}")


RMSE: 21.10405582209896
R^2 Score: 0.9999545812606812
